### PR TITLE
command ops test

### PR DESCRIPTION
**Pull request by NotMyFault**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
With https://github.com/jenkinsci/.github/pull/91 merged, isn't `/reviewer` supposed to be enabled globally?

cc @timja 👀

**Comment by timja** [comment]
Not yet I haven’t released the version yet that is disabled by default or requested enabling it globally

**Comment by NotMyFault** [comment]
> Not yet I haven’t released the version yet that is disabled by default or requested enabling it globally

Oic!

**Pull request closed without merging**
