### PR TITLE
Setup security scan

### PR DESCRIPTION
**Pull request by NotMyFault**
Let's see how this works...

### CODE REVIEW

**Comment by olamy** [comment]
would be nice to have this available as a step to add in `Jenkinsfile` for use in https://ci.jenkins.io/

**Comment by NotMyFault** [comment]
> would be nice to have this available as a step to add in `Jenkinsfile` for use in https://ci.jenkins.io/

The action was explicitly created for GitHub workflows for GitHub's GraphQL integration allowing you to run it alongside building on Jenkins. Would be interesting to see if you can integrate it elsewhere nevertheless 👀

**Comment by olamy** [comment]
> > would be nice to have this available as a step to add in `Jenkinsfile` for use in https://ci.jenkins.io/
> 
> The action was explicitly created for GitHub workflows for GitHub's GraphQL integration allowing you to run it alongside building on Jenkins. Would be interesting to see if you can integrate it elsewhere nevertheless 👀

Maybe I misunderstand something but the idea is to run [codeql](https://codeql.github.com/) not sure what you mean with GraphQL?

**Comment by NotMyFault** [comment]
> Maybe I misunderstand something but the idea is to run [codeql](https://codeql.github.com/) not sure what you mean with GraphQL?

Yeah, but apparently my phone was not aware of that word and autocorrected it :P

**Comment by olamy** [comment]
https://github.com/jenkinsci/codeql-plugin

**Pull request merged**
